{% set name = "hits" %}
{% set version = "0.5.0" %}
{% set sha256 = "423332cc9973fc3f90b82b629812b009e0b93423d658e12137c736268bc7fec6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name  }}-{{ version }}.tar.gz"
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [osx and x86_64]
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv
  run_exports:
    - {{ pin_subpackage('hits', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python
    - biopython >=1.72
    - bokeh >=3.2
    - ipython >=7.8.0
    - ipywidgets >=7.4.2
    - matplotlib-base >=3.0.2
    - numpy >=1.15.4
    - pandas >=0.23.4
    - pillow >=5.3.0
    - pysam >=0.15.1
    - pyyaml >=3.13
    - s3fs
    - scipy >=1.2.1
    - seaborn-base >=0.11.0
    - statsmodels >=0.12.1

test:
  imports:
    - hits

about:
  home: "https://github.com/jeffhussmann/hits"
  summary: "Utilities for processing high-throughput sequencing experiments."
  license: "GPL-3.0-or-later"
  license_family: GPL3
  license_file: LICENSE
  dev_url: "https://github.com/jeffhussmann/hits"
  doc_url: "https://github.com/jeffhussmann/hits/blob/v{{ version }}/README.md"

extra:
  recipe-maintainers:
    - jeffhussmann
  additional-platforms:
    - linux-aarch64
    - osx-arm64
